name: Validate
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: "-Csplit-debuginfo=packed"
      CARGO_BUILD_JOBS: 1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set Build Tools and update Rust
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup component add clippy

      - name: Use ffmpeg on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Tests and build on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cargo test --all-features
          cargo clippy --all-features --all-targets -- --deny warnings
          cargo fmt --all -- --check
          cargo build --all-features --verbose

      - name: Run build on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: cargo build --all-features --verbose

      - name: Run build on Windows (with MSVC fixes)
        if: ${{ matrix.os == 'windows-latest' }}
        run: cargo build --release --all-features --verbose
